/*
 * dma.c
 *
 *  Created on: Nov 28, 2016
 *      Author: shva9978
 */



#include <stdint.h>
#include "dma.h"
#include "math.h"
#include "MKL25Z4.h"
#include "memory.h"
#include "mcg.h"
#include "timer.h"
#define LENGTH 500

#include "uart.h"


char  g8bSource[LENGTH]= "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
char  g8Destiny[LENGTH];
int length=LENGTH;

void UART0_init(void)   //initialization function for UART
{

	__disable_irq();
	    SIM->SCGC5 |= SIM_SCGC5_PORTA_MASK;
		SIM->SCGC4 |= SIM_SCGC4_UART0_MASK;
		SIM->SOPT2 |= SIM_SOPT2_UART0SRC(1);

		PORTA->PCR[2]= PORT_PCR_MUX(2);
		PORTA->PCR[1]= PORT_PCR_MUX(2);

		UART0->C2 = 0x00;
		UART0->C1 = 0x00;
		UART0->BDH = 0x00;
		UART0->BDL = 0x17;
		//UART0->C4 = 0x0F;

		//UART_C2_REG(UART0_BASE_PTR) |= UART_C2_TIE_MASK;//Setup receiver interrupt
		UART_C2_REG(UART0_BASE_PTR) |= UART_C2_RIE_MASK;
		UART_C2_REG(UART0_BASE_PTR) |= UART_C2_RE_MASK;//(UART_C2_TE_MASK | UART_C2_RE_MASK );

		__enable_irq();
	    NVIC_EnableIRQ(UART0_IRQn);
		//NVIC->ISER[0] |= 0x00001000;


}

void init_DMA_1Trans()   // DMA initialization function

{

			SIM_SCGC6 |= SIM_SCGC6_DMAMUX_MASK;
			SIM_SCGC7 |= SIM_SCGC7_DMA_MASK;

			DMAMUX0_CHCFG0 = 0x00;
			DMA0->DMA[0].DSR_BCR= DMA_DSR_BCR_DONE_MASK;
			DMA_DSR_BCR0 |= length;
			DMA_SAR0 = (uint32_t)g8bSource;
			DMA_DAR0 = (uint32_t)g8Destiny;
			DMA_DCR0 |= DMA_DCR_EINT_MASK;
			DMA_DCR0 |= DMA_DCR_AA_MASK;
			DMA_DCR0 |= DMA_DCR_SSIZE(1)|DMA_DCR_DSIZE(1);

			DMA_DCR0 |= DMA_DCR_SINC_MASK;
			DMA_DCR0 |= DMA_DCR_DINC_MASK;

			DMAMUX0_CHCFG0 |= DMAMUX_CHCFG_ENBL_MASK;
			__enable_irq();
			//NVIC_EnableIRQ(DMA0_IRQn);

			profiler_start();
			DMA_DCR0 |= DMA_DCR_START_MASK;
			//DMA_DSR_BCR0 |= 0x1000000u;

}


int main()
{

	__disable_irq();
	UART0_init();
	init_DMA_1Trans();

	return 0;

}


